version: '3.3'
services:
  soap:
    image: senchenkodv/soap
    restart: always
    build: /
    working_dir: /integration
    volumes:
      - ./integration:/integration
    expose:
      - "8080"
    command: mvn clean spring-boot:run