services: '3.3'

  integration:
    image: senchenkodv/integration
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
  soap:
    image: senchenkodv/soap
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local