version: '3.3'
services:
  soap:
    image: senchenkodv/soap
    restart: always
    build: soapWeatherServer
    working_dir: /soapWeatherServer
    volumes:
      - ./soapWeatherServer:/soapWeatherServer
    expose:
      - "8080"
    command: mvn clean spring-boot:run